-- ============================================================
--  SUPERSEDED — this file is no longer the schema.
--
--  The schema now lives in supabase/migrations/, applied in order
--  and tracked in a schema_migrations table so each file runs once:
--
--    0001_baseline.sql          tables, enums, triggers, base RLS
--    0002_tasks.sql             tasks
--    0003_digests_and_sla.sql   digests + the SLA follow-up types
--    0004_role_permissions.sql  per-verb, role-aware RLS
--
--  Apply them with:
--    npm run db:apply           # pending migrations
--    npm run db:apply:seed      # migrations + seed data
--    npm run db:status          # what is applied, what is pending
--
--  To change the schema, add the NEXT numbered file in
--  supabase/migrations/. Never edit a migration that has already
--  run — two databases would silently diverge. The runner warns
--  when a file's checksum no longer matches what it applied.
--
--  This file is intentionally left as comments only: it is a valid
--  no-op if anyone still pastes it into the SQL editor out of habit.
-- ============================================================
